# Generated by Django 6.0.6 on 2026-06-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_utente', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='quiz.quiz')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='quiz.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('testo', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domande', to='quiz.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('testo', models.TextField()),
                ('tipo', models.CharField(choices=[('Corretta', 'Corretta'), ('Sbagliata', 'Sbagliata')], max_length=10)),
                ('punteggio', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='quiz.domanda')),
            ],
            options={
                'unique_together': {('domanda', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_creati', to='quiz.utente'),
        ),
        migrations.CreateModel(
            name='RispostaUtenteQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.domanda')),
                ('partecipazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte_date', to='quiz.partecipazione')),
                ('risposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.risposta')),
            ],
            options={
                'verbose_name_plural': 'Risposte Utente Quiz',
                'unique_together': {('partecipazione', 'domanda')},
            },
        ),
    ]
